 A partir del dataset FinancialPhraseBank utilizando unicamente las frases financieras con un 100% de coincidencia en la etiqueta realizar las siguientes tareas:

· Bag of words

· TF-IDF

· Word-to-vect 

Bag of Words

In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
#from sklearn.sklearn.ensemble import RandomForestClassifier

In [2]:
#Leo los datos

dataset = pd.read_csv('C:\\Users\\ignac\\OneDrive\\Escritorio\\BME\\Master\\CLASES\\Modulo 4\\Lenguage Natural\\Practica\\Financial_Phrases\\Sentences_AllAgree.txt', encoding='latin1', delimiter='@', header=None)
dataset

0         1
0     According to Gran , the company has no plans t...   neutral
1     For the last quarter of 2010 , Componenta 's n...  positive
2     In the third quarter of 2010 , net sales incre...  positive
3     Operating profit rose to EUR 13.1 mn from EUR ...  positive
4     Operating profit totalled EUR 21.1 mn , up fro...  positive
...                                                 ...       ...
2259  Operating result for the 12-month period decre...  negative
2260  HELSINKI Thomson Financial - Shares in Cargote...  negative
2261  LONDON MarketWatch -- Share prices ended lower...  negative
2262  Operating profit fell to EUR 35.4 mn from EUR ...  negative
2263  Sales in Finland decreased by 10.5 % in Januar...  negative

[2264 rows x 2 columns]

In [3]:
#Creo una instancia con CountVectorizer y entreno sobre el dataset

vect = CountVectorizer()
vect.fit(dataset[0])

CountVectorizer()

In [4]:
#Creo un vocabulario en el cual filtra y asigna etiquetas a las palabras y content hace un diccionario de las palabras indexando las etiquetas del vocabulario

print('Tamaño del vocabulario: {}'.format(len(vect.vocabulary_)))
print('Contenido del vocabulario:\n {}'.format(vect.vocabulary_))

Tamaño del vocabulario: 6057
Contenido del vocabulario:
 {'according': 566, 'to': 5528, 'gran': 2621, 'the': 5471, 'company': 1434, 'has': 2696, 'no': 3824, 'plans': 4206, 'move': 3701, 'all': 685, 'production': 4361, 'russia': 4763, 'although': 706, 'that': 5470, 'is': 3018, 'where': 5920, 'growing': 2640, 'for': 2449, 'last': 3238, 'quarter': 4449, 'of': 3891, '2010': 172, 'componenta': 1456, 'net': 3788, 'sales': 4795, 'doubled': 1857, 'eur131m': 2099, 'from': 2504, 'eur76m': 2186, 'same': 4801, 'period': 4145, 'year': 6005, 'earlier': 1912, 'while': 5925, 'it': 3032, 'moved': 3702, 'zero': 6028, 'pre': 4292, 'tax': 5406, 'profit': 4369, 'loss': 3385, 'eur7m': 2187, 'in': 2866, 'third': 5491, 'increased': 2880, 'by': 1167, 'eur': 2084, '205': 178, 'mn': 3649, 'and': 742, 'operating': 3939, '34': 262, '23': 195, 'rose': 4732, '13': 76, 'corresponding': 1573, '2007': 166, 'representing': 4636, 'totalled': 5554, '21': 182, 'up': 5697, '18': 123, 'finnish': 2388, 'talentum': 5375, 'repo

In [5]:
#Transformo el dataset en una Bag of Words en el cual pasa donde esta la frase y la etiqueta asignada a esa palabra
BoW = vect.transform(dataset[0])
print(BoW)

  (0, 566)	1
  (0, 685)	1
  (0, 706)	1
  (0, 1434)	2
  (0, 2621)	1
  (0, 2640)	1
  (0, 2696)	1
  (0, 3018)	2
  (0, 3701)	1
  (0, 3824)	1
  (0, 4206)	1
  (0, 4361)	1
  (0, 4763)	1
  (0, 5470)	1
  (0, 5471)	2
  (0, 5528)	3
  (0, 5920)	1
  (1, 172)	1
  (1, 1456)	1
  (1, 1857)	1
  (1, 1912)	1
  (1, 2099)	1
  (1, 2186)	1
  (1, 2187)	1
  (1, 2449)	2
  :	:
  (2262, 427)	1
  (2262, 2084)	3
  (2262, 2339)	1
  (2262, 2504)	1
  (2262, 2535)	1
  (2262, 2866)	1
  (2262, 2874)	1
  (2262, 3649)	3
  (2262, 3891)	1
  (2262, 3939)	1
  (2262, 4369)	1
  (2262, 4795)	1
  (2262, 5528)	1
  (2262, 5790)	1
  (2263, 38)	1
  (2263, 113)	1
  (2263, 1167)	2
  (2263, 1702)	1
  (2263, 1875)	1
  (2263, 2386)	2
  (2263, 2866)	2
  (2263, 3053)	1
  (2263, 4006)	1
  (2263, 4795)	2
  (2263, 5925)	1


In [6]:
#Creo un array con mi variable BoW, en el que toda la bolsa esta representada
print('BoW como un array:\n{}'.format(BoW.toarray()))

BoW como un array:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [7]:
#Creo una lista de las palabras unicas
vect.get_feature_names()

['00',
 '000',
 '002',
 '0025',
 '003',
 '0030',
 '007',
 '008',
 '01',
 '0101138',
 '012',
 '019',
 '02',
 '023',
 '027',
 '03',
 '030',
 '031',
 '04',
 '045',
 '047',
 '05',
 '050',
 '052',
 '06',
 '063',
 '07',
 '070',
 '0711',
 '0762',
 '08',
 '083',
 '084',
 '087',
 '089',
 '09',
 '094',
 '097',
 '10',
 '100',
 '1000',
 '100mn',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109mn',
 '10mn',
 '11',
 '110',
 '111',
 '1112',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '117mn',
 '118',
 '119',
 '11m',
 '12',
 '120',
 '1200',
 '121',
 '122',
 '123',
 '124',
 '128',
 '129',
 '12mp',
 '13',
 '130',
 '131',
 '132',
 '133',
 '135',
 '138',
 '139',
 '14',
 '140',
 '1411',
 '142',
 '143',
 '145',
 '146',
 '146mn',
 '149',
 '15',
 '150',
 '150mn',
 '151',
 '152',
 '154',
 '155',
 '156',
 '158',
 '159',
 '16',
 '160',
 '161',
 '162',
 '163',
 '164',
 '1649',
 '165',
 '167',
 '168',
 '17',
 '170',
 '172',
 '172p',
 '173',
 '174',
 '175',
 '177mn',
 '179mn',
 '17m',
 '18

TF-IDF

In [8]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
#Vectorizo y entreno la variable vectorizada
tf=TfidfVectorizer()
text_tf= tf.fit_transform(dataset[0])

In [10]:
#Creo una matriz densa en la cualestablecere las posiciones paara cada palabra
dense_matrix = pd.DataFrame(text_tf.todense())
dense_matrix

0     1     2     3     4     5     6     7     8     9     ...  6047  \
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
2259   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2260   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2261   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2262   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2263   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

      6048  6049  6050  6051  6052  6053  6054  6055  6056  
0      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
2259   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2260   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2261   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2262   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2263   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[2264 rows x 6057 columns]

In [11]:
import nltk
from nltk.corpus import stopwords
from sklearn.preprocessing import LabelEncoder
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
#nltk.download('stopwords')
#stop = stopwords.words('@')

In [12]:
#Prueba TF IDF

palabras_unicas = set(dataset[0])
print(palabras_unicas)

{'Ahlstrom Corporation STOCK EXCHANGE ANNOUNCEMENT 23.4.2007 Ahlstrom Corporation will publish its first quarter financial results 2007 on Friday , April 27 , 2007 approximately at 8.30 a.m. Finnish time .', 'The measures taken will cause one-time costs during the final part of 2006 .', 'These financing arrangements will enable the company to ensure , in line with its treasury policy , that it has sufficient financial instruments at its disposal for its potential capital requirements .', "The company 's net profit rose 11.4 % on the year to 82.2 million euros in 2005 on sales of 686.5 million euros , 13.8 % up on the year , the company said earlier .", "STOCKMANN plc COMPANY ANNOUNCEMENT February 20 , 2007 , at 13.40 An annual summary of Stockmann 's stock exchange and financial press releases in 2006 is available on the company 's website at the address www.stockmann.com .", '- Net sales for the period are expected to fall well below that of last year and the result after non-recurrin

In [13]:
#Creo un diccionario de palabras unicas y veo cuantas veces se repiten en el texto
#PERO ME SALEN LAS PUTAS FRASES Y NO POR PALABRAS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
numero_palabras = dict.fromkeys(palabras_unicas, 0)
for palabra in dataset[0]:
    numero_palabras[palabra] += 1

print(numero_palabras)

{'Ahlstrom Corporation STOCK EXCHANGE ANNOUNCEMENT 23.4.2007 Ahlstrom Corporation will publish its first quarter financial results 2007 on Friday , April 27 , 2007 approximately at 8.30 a.m. Finnish time .': 1, 'The measures taken will cause one-time costs during the final part of 2006 .': 1, 'These financing arrangements will enable the company to ensure , in line with its treasury policy , that it has sufficient financial instruments at its disposal for its potential capital requirements .': 1, "The company 's net profit rose 11.4 % on the year to 82.2 million euros in 2005 on sales of 686.5 million euros , 13.8 % up on the year , the company said earlier .": 1, "STOCKMANN plc COMPANY ANNOUNCEMENT February 20 , 2007 , at 13.40 An annual summary of Stockmann 's stock exchange and financial press releases in 2006 is available on the company 's website at the address www.stockmann.com .": 1, '- Net sales for the period are expected to fall well below that of last year and the result aft

In [14]:
from  nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [15]:
#Asi hago la formula matematica de TF-IDF, en la que saca el numero de veces en el que la palabra aparece en el texto dividido entre el num total
#de palabras en el texto

def computeTF(diccionario_palabra, Bag_Of_Words):
    tf_dict = {}
    Contar_BagOfWords = len(Bag_Of_Words)
    for palabra, contar in diccionario_palabra.items():
        tf_dict[palabra] = contar / float(Contar_BagOfWords)
    return tf_dict

In [16]:
#APARECE LA PROBABILIDAD ASOCIADA A LA FRASE, HABLARLO CON ALGUIEN
tf_texto = computeTF(numero_palabras, dataset[0])
print(tf_texto)

{'Ahlstrom Corporation STOCK EXCHANGE ANNOUNCEMENT 23.4.2007 Ahlstrom Corporation will publish its first quarter financial results 2007 on Friday , April 27 , 2007 approximately at 8.30 a.m. Finnish time .': 0.00044169611307420494, 'The measures taken will cause one-time costs during the final part of 2006 .': 0.00044169611307420494, 'These financing arrangements will enable the company to ensure , in line with its treasury policy , that it has sufficient financial instruments at its disposal for its potential capital requirements .': 0.00044169611307420494, "The company 's net profit rose 11.4 % on the year to 82.2 million euros in 2005 on sales of 686.5 million euros , 13.8 % up on the year , the company said earlier .": 0.00044169611307420494, "STOCKMANN plc COMPANY ANNOUNCEMENT February 20 , 2007 , at 13.40 An annual summary of Stockmann 's stock exchange and financial press releases in 2006 is available on the company 's website at the address www.stockmann.com .": 0.0004416961130

In [17]:
#Hgo la frecuencia inversa, IDF(Inverse Data Frequency), esto es el numero logaritmico del documento dividido entre el numero de documentos que conteien
#la palabra W.
#IDF determiena el peso de las palabras raras a lo largo del cuerpò del documento

import math

def computeIDF(documentos):
    n = len(documentos)

    idf_diccionario = dict.fromkeys(documentos[0].keys(),0)
    for documento in documentos:
        for palabra, val in documento.items():
            if val > 0:
                idf_diccionario[palabra] += 1

    for palabra, val in idf_diccionario.items():
        idf_diccionario[palabra] = math.log(n / float(val))
    return idf_diccionario

In [18]:
idf = computeIDF([numero_palabras])

In [19]:
#Ahora junto TF y IDF  multiplicandolos para crear TF-IDF

def computeTFIDF(tfBagOfWords, idf):
    tfidf = {}
    for palabra, val in tfBagOfWords.items():
        tfidf[palabra] = val * idf[palabra]
    return tfidf

In [20]:
tfidf = computeTFIDF(tf_texto, idf)
df = pd.DataFrame([tfidf])

In [21]:
df

Ahlstrom Corporation STOCK EXCHANGE ANNOUNCEMENT 23.4.2007 Ahlstrom Corporation will publish its first quarter financial results 2007 on Friday , April 27 , 2007 approximately at 8.30 a.m. Finnish time .  \
0                                                0.0                                                                                                                                                             

   The measures taken will cause one-time costs during the final part of 2006 .  \
0                                                0.0                              

   These financing arrangements will enable the company to ensure , in line with its treasury policy , that it has sufficient financial instruments at its disposal for its potential capital requirements .  \
0                                                0.0                                                                                                                                                           

   The company 's net profit rose 11.4 % on the year to 82.2 million euros in 2005 on sales of 686.5 million euros , 13.8 % up on the year , the company said earlier .  \
0                                                0.0                                                                                                                      

   STOCKMANN plc COMPANY ANNOUNCEMENT February 20 , 2007 , at 13.40 An annual summary of Stockmann 's stock exchange and financial press releases in 2006 is available on the company 's website at the address www.stockmann.com .  \
0                                                0.0                                                                                                                                                                                  

   - Net sales for the period are expected to fall well below that of last year and the result after non-recurring items is expected to be in the red .  \
0                                                0.0                                                                                                      

   Finnish financial group Aktia reports operating profit of EUR 44.4 mn in January-September 2009 , up from EUR 37.3 mn in the corresponding period in 2008 .  \
0                                                0.0                                                                                                             

   SDM offers general rental equipment , aluminium scaffolding , power generator and hoists to customers in the construction sector .  \
0                                                0.0                                                                                    

   An  of the invention , released by the Patent Office , said : `` A non-coherent search matrix is formed of said correlation function matrix .  \
0                                                0.0                                                                                               

   CapMan has four investment areas ( CapMan Buyout , CapMan Technology , CapMan Life Science and CapMan Real Estate ) , and each of them has a dedicated team .  \
0                                                0.0                                                                                                               

   ...  The deal was worth about EUR 1.2 mn .  \
0  ...                                    0.0   

   A paper mill in the central Maine town of Madison soon will have a new owner .  \
0                                                0.0                                

   The company continued the development of a fully human antibody in its VAP-1 antibody program .  \
0                                                0.0                                                 

   Jon Risfelt is 49 years old holds a Master of Science in Chemical Engineering from the Swedish Royal Institute of Technology .  \
0                                              

In [22]:
#REVISAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR!!!!!!!!!!!!!!!!11
#vectorizer = TFIDF_vectorizer()
#vectores = vectorizer.fit_transform([document])
#featured_names = vectorizer.get_feature_names()
#dense = vectores.todense()
#lista_dense = dense.tolist()
#df = pd.DataFrame(lista_dense, columns=featured_names)

WORD 2 VECT

In [23]:
!pip install gensim

In [24]:
import gensim
from gensim.models import word2vec, KeyedVectors
import nltk
nltk.download('punkt')
from keras.preprocessing import text
from nltk.corpus import stopwords

from keras.preprocessing.sequence import skipgrams
from tensorflow.keras.layers import Dot
from keras.layers.core import Dense, Reshape
from keras.layers.embeddings import Embedding
from keras.models import Sequential
from keras.layers import Input
from keras.models import Model
from keras.layers.embeddings import Embedding
from keras.layers.core import Dense, Reshape
from keras.layers import dot
from keras.preprocessing.sequence import skipgrams
from keras.layers import Flatten

C:\Users\ignac\Anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ignac\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [25]:
dataset_vect = dataset
dataset_vect.columns = ['texto', 'sentimiento']
dataset_vect

texto sentimiento
0     According to Gran , the company has no plans t...     neutral
1     For the last quarter of 2010 , Componenta 's n...    positive
2     In the third quarter of 2010 , net sales incre...    positive
3     Operating profit rose to EUR 13.1 mn from EUR ...    positive
4     Operating profit totalled EUR 21.1 mn , up fro...    positive
...                                                 ...         ...
2259  Operating result for the 12-month period decre...    negative
2260  HELSINKI Thomson Financial - Shares in Cargote...    negative
2261  LONDON MarketWatch -- Share prices ended lower...    negative
2262  Operating profit fell to EUR 35.4 mn from EUR ...    negative
2263  Sales in Finland decreased by 10.5 % in Januar...    negative

[2264 rows x 2 columns]

In [27]:
#Tokenizo las palabras de la columna Texto

texto = dataset.texto

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(texto)

In [28]:
w2id = tokenizer.word_index
id2w = {v:k for k, v in w2id.items()}

vocab_size = len(w2id) + 1 
embed_size = 100

In [29]:
#Asigno un numero unico a cada palabra de cada frase

wids = [[w2id[w] for w in text.text_to_word_sequence(doc)] for doc in texto]
print('Vocabulary Size:', vocab_size)
print('Vocabulary Sample:', list(w2id.items())[:10])

Vocabulary Size: 6110
Vocabulary Sample: [('the', 1), ('of', 2), ('in', 3), ('and', 4), ('to', 5), ('eur', 6), ('a', 7), ('for', 8), ('from', 9), ("'s", 10)]


In [30]:
#Generate skip grams
skip_grams = [skipgrams(wid, vocabulary_size=vocab_size, window_size=10) for wid in wids]

#Veo los skip grams
pairs, labels = skip_grams[0][0], skip_grams[0][1]
for i in range(10):
    print("({:s} ({:d}), {:s} ({:d})) -> {:d}".format(
          id2w[pairs[i][0]], pairs[i][0], 
          id2w[pairs[i][1]], pairs[i][1], 
          labels[i]))

(where (458), innovation (2186)) -> 0
(company (13), else (4954)) -> 0
(production (137), plans (1271)) -> 1
(has (42), production (137)) -> 1
(russia (174), although (1948)) -> 1
(to (5), loyal (3781)) -> 0
(plans (1271), eua (4767)) -> 0
(company (13), issue (513)) -> 0
(production (137), game (2725)) -> 0
(the (1), digital (817)) -> 0


In [31]:
stop = stopwords.words('english')

In [32]:
#Construyo el modelo
dataset['texto_limpio'] = dataset['texto'].apply(
    lambda x: ' '.join(
        [word.lower() for word in x.split() 
        if word not in (stop) and word.isalnum()]
        )
    )
dataset.head(4)

lb = LabelEncoder()
sentimientos = lb.fit_transform(dataset.sentimiento)
aleat = np.random.choice(dataset.shape[0], 2000, replace=False)
X = dataset.texto_limpio.iloc[aleat]
X_test = dataset.texto_limpio.iloc[~aleat]
y = sentimientos[aleat]
y_test = sentimientos[~aleat]

In [33]:
input_a = Input(shape=1)
embedding_a = Embedding(
    input_dim = vocab_size,
    output_dim = embed_size,
    input_length=1)(input_a)

flatten_a = Flatten()(embedding_a)

input_b = Input(shape=1)
embedding_b = Embedding(
    input_dim = vocab_size,
    output_dim = embed_size,
    input_length=1)(input_b)
flatten_b = Flatten()(embedding_b)

prodes = dot([flatten_a, flatten_b], axes=1)

densa = Dense(1,activation="sigmoid")(prodes)

modelo = Model(inputs=[input_a, input_b], outputs=[densa])
modelo.compile(loss="binary_crossentropy", metrics=["accuracy"])
modelo.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 1)]          0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 1, 100)       611000      input_1[0][0]                    
__________________________________________________________________________________________________
embedding_1 (Embedding)         (None, 1, 100)       611000      input_2[0][0]                    
______________________________________________________________________________________________

In [34]:
#REVISAAAAAAAAAARLOOOOOOOOOOO LINEA: PAIR_FIRST_ELEM
#for epoch in range(1, 5):
 #   loss = 0
  #  for i, elem in enumerate(skip_grams):
   #     pair_first_elem = np.array(list(zip(*elem[0]))[0], dtype='int32')
    #    pair_second_elem = np.array(list(zip(*elem[0]))[1], dtype='int32')
     #   labels = np.array(elem[1], dtype='int32')
      #  X = [pair_first_elem, pair_second_elem]
       # Y = labels
        #if i % 10000 == 0:
         #   print('Processed {} (skip_first, skip_second, relevance) pairs'.format(i))
        #loss = modelo.train_on_batch(X,Y)  

    #print('Epoch:', epoch, 'Loss:', loss)

In [35]:
#me creo un df solo con el texto
#nuevos_titulos = dataset[0]

In [36]:
#Tokenizo las palabras para cada frase

#nuevo_vector =  [nltk.word_tokenize(titulo) for titulo in nuevos_titulos]
#nuevo_vector

In [37]:
#model_w2v = gensim.models.word2vec(nuevo_vector, min_count=1)

In [38]:
#Vectorizo todo

#vectorizer = TFIDF_vectorizer()
#vectores = vectorizer.fit_transform([document])
#featured_names = vectorizer.get_feature_names()
#dense = vectores.todense()
#lista_dense = dense.tolist()
#df = pd.DataFrame(lista_dense, columns=featured_names)